"""modified activity, added date

Revision ID: 05004f4b1065
Revises: 4457e2ce796f
Create Date: 2025-01-06 09:16:49.244748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05004f4b1065'
down_revision: Union[str, None] = '4457e2ce796f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('date', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'date')
    # ### end Alembic commands ###
