"""modified settings table

Revision ID: 1aacf5bd5b46
Revises: cce8140be58b
Create Date: 2025-01-04 21:25:10.114475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aacf5bd5b46'
down_revision: Union[str, None] = 'cce8140be58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_settings_league_year', table_name='settings')
    op.drop_constraint('uix_settings_league_year', 'settings', type_='unique')
    op.create_index('idx_settings_league', 'settings', ['league_id'], unique=False)
    op.create_unique_constraint(None, 'settings', ['league_id'])
    op.drop_column('settings', 'year')
    op.drop_column('settings', 'leagueId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('leagueId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('settings', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'settings', type_='unique')
    op.drop_index('idx_settings_league', table_name='settings')
    op.create_unique_constraint('uix_settings_league_year', 'settings', ['leagueId', 'year'])
    op.create_index('idx_settings_league_year', 'settings', ['leagueId', 'year'], unique=False)
    # ### end Alembic commands ###
