"""updated league

Revision ID: 290dfac54bb3
Revises: cc8595ff7df7
Create Date: 2024-12-31 07:16:57.623927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '290dfac54bb3'
down_revision: Union[str, None] = 'cc8595ff7df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leagues', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'leagues', ['year'])
    op.drop_column('leagues', 'reg_season_count')
    op.drop_column('leagues', 'name')
    op.drop_column('leagues', 'veto_votes_required')
    op.drop_column('leagues', 'previous_seasons')
    op.drop_column('teams', 'owners')
    op.drop_column('teams', 'schedule')
    op.drop_column('teams', 'scores')
    op.drop_column('teams', 'outcomes')
    op.drop_column('teams', 'stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('stats', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('outcomes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('schedule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('owners', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('leagues', sa.Column('previous_seasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('leagues', sa.Column('veto_votes_required', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leagues', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('leagues', sa.Column('reg_season_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leagues', type_='unique')
    op.alter_column('leagues', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
