"""added Player unique constraint espnId/name

Revision ID: 2ee3a7c5c63b
Revises: 8e30060d7332
Create Date: 2025-01-04 15:13:16.821593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee3a7c5c63b'
down_revision: Union[str, None] = '8e30060d7332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_player_espnId_name', 'players', ['espnId', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_player_espnId_name', 'players', type_='unique')
    # ### end Alembic commands ###
