"""modified settings table, value types were incorrect

Revision ID: 42497e04be8f
Revises: 1aacf5bd5b46
Create Date: 2025-01-04 21:56:18.262894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42497e04be8f'
down_revision: Union[str, None] = '1aacf5bd5b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
