"""modified activity table

Revision ID: 4457e2ce796f
Revises: b47e6ffd5115
Create Date: 2025-01-06 09:14:22.422887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4457e2ce796f'
down_revision: Union[str, None] = 'b47e6ffd5115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_league_year', table_name='activities')
    op.create_index('idx_activity_team_player', 'activities', ['team_id', 'player_id'], unique=False)
    op.drop_constraint('activities_league_id_fkey', 'activities', type_='foreignkey')
    op.drop_column('activities', 'year')
    op.drop_column('activities', 'league_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('activities', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('activities_league_id_fkey', 'activities', 'leagues', ['league_id'], ['id'])
    op.drop_index('idx_activity_team_player', table_name='activities')
    op.create_index('idx_activity_league_year', 'activities', ['league_id', 'year'], unique=False)
    # ### end Alembic commands ###
