"""Expanded all tables

Revision ID: 559ec8087427
Revises: 08b625295f76
Create Date: 2024-12-30 14:08:44.892571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559ec8087427'
down_revision: Union[str, None] = '08b625295f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('reg_season_count', sa.Integer(), nullable=True),
    sa.Column('veto_votes_required', sa.Integer(), nullable=True),
    sa.Column('team_count', sa.Integer(), nullable=True),
    sa.Column('playoff_team_count', sa.Integer(), nullable=True),
    sa.Column('keeper_count', sa.Integer(), nullable=True),
    sa.Column('trade_deadline', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tie_rule', sa.Integer(), nullable=True),
    sa.Column('playoff_tie_rule', sa.Integer(), nullable=True),
    sa.Column('playoff_seed_tie_rule', sa.Integer(), nullable=True),
    sa.Column('playoff_matchup_period_length', sa.Integer(), nullable=True),
    sa.Column('faab', sa.Boolean(), nullable=True),
    sa.Column('scoring_format', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('box_scores', sa.Column('home_projected', sa.Float(), nullable=True))
    op.add_column('box_scores', sa.Column('away_projected', sa.Float(), nullable=True))
    op.add_column('box_scores', sa.Column('is_playoff', sa.Boolean(), nullable=True))
    op.add_column('box_scores', sa.Column('matchup_type', sa.String(length=50), nullable=True))
    op.alter_column('box_scores', 'home_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('box_scores', 'away_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('drafts', sa.Column('bid_amount', sa.Integer(), nullable=True))
    op.add_column('drafts', sa.Column('keeper_status', sa.Boolean(), nullable=True))
    op.add_column('drafts', sa.Column('nominating_team_id', sa.Integer(), nullable=True))
    op.alter_column('drafts', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('drafts', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('drafts', 'round_num',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('drafts', 'round_pick',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'drafts', 'teams', ['nominating_team_id'], ['id'])
    op.add_column('leagues', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('current_week', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('nfl_week', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('previous_seasons', sa.JSON(), nullable=True))
    op.add_column('matchups', sa.Column('is_playoff', sa.Boolean(), nullable=True))
    op.add_column('matchups', sa.Column('matchup_type', sa.String(length=50), nullable=True))
    op.alter_column('matchups', 'home_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matchups', 'away_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('teams', sa.Column('team_id', sa.Integer(), nullable=False))
    op.add_column('teams', sa.Column('team_abbrev', sa.String(length=10), nullable=False))
    op.add_column('teams', sa.Column('division_id', sa.String(length=255), nullable=True))
    op.add_column('teams', sa.Column('division_name', sa.String(length=255), nullable=True))
    op.add_column('teams', sa.Column('ties', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('points_for', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('points_against', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('waiver_rank', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('acquisitions', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('acquisition_budget_spent', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('drops', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('trades', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('owners', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('stats', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('streak_type', sa.String(length=50), nullable=True))
    op.add_column('teams', sa.Column('streak_length', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('standing', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('draft_projected_rank', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('playoff_pct', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('logo_url', sa.String(length=255), nullable=True))
    op.add_column('teams', sa.Column('schedule', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('scores', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('outcomes', sa.JSON(), nullable=True))
    op.alter_column('teams', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'teams', ['team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.alter_column('teams', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('teams', 'outcomes')
    op.drop_column('teams', 'scores')
    op.drop_column('teams', 'schedule')
    op.drop_column('teams', 'logo_url')
    op.drop_column('teams', 'playoff_pct')
    op.drop_column('teams', 'draft_projected_rank')
    op.drop_column('teams', 'standing')
    op.drop_column('teams', 'streak_length')
    op.drop_column('teams', 'streak_type')
    op.drop_column('teams', 'stats')
    op.drop_column('teams', 'owners')
    op.drop_column('teams', 'trades')
    op.drop_column('teams', 'drops')
    op.drop_column('teams', 'acquisition_budget_spent')
    op.drop_column('teams', 'acquisitions')
    op.drop_column('teams', 'waiver_rank')
    op.drop_column('teams', 'points_against')
    op.drop_column('teams', 'points_for')
    op.drop_column('teams', 'ties')
    op.drop_column('teams', 'division_name')
    op.drop_column('teams', 'division_id')
    op.drop_column('teams', 'team_abbrev')
    op.drop_column('teams', 'team_id')
    op.alter_column('matchups', 'away_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matchups', 'home_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('matchups', 'matchup_type')
    op.drop_column('matchups', 'is_playoff')
    op.drop_column('leagues', 'previous_seasons')
    op.drop_column('leagues', 'nfl_week')
    op.drop_column('leagues', 'current_week')
    op.drop_column('leagues', 'year')
    op.drop_constraint(None, 'drafts', type_='foreignkey')
    op.alter_column('drafts', 'round_pick',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('drafts', 'round_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('drafts', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('drafts', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('drafts', 'nominating_team_id')
    op.drop_column('drafts', 'keeper_status')
    op.drop_column('drafts', 'bid_amount')
    op.alter_column('box_scores', 'away_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('box_scores', 'home_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('box_scores', 'matchup_type')
    op.drop_column('box_scores', 'is_playoff')
    op.drop_column('box_scores', 'away_projected')
    op.drop_column('box_scores', 'home_projected')
    op.drop_table('settings')
    # ### end Alembic commands ###
