"""complete refactor

Revision ID: 72e0ebb96207
Revises: d5f69b4ada51
Create Date: 2025-01-01 07:17:33.347011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e0ebb96207'
down_revision: Union[str, None] = 'd5f69b4ada51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('leagueId', sa.Integer(), nullable=False),
    sa.Column('teamCount', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('currentWeek', sa.Integer(), nullable=True),
    sa.Column('nflWeek', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('leagueId'),
    sa.UniqueConstraint('year'),
    sa.UniqueConstraint('year', name='uix_league_year')
    )
    op.create_index('idx_league_year', 'leagues', ['year'], unique=False)
    op.create_table('players',
    sa.Column('playerId', sa.Integer(), nullable=False),
    sa.Column('leagueId', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('proTeam', sa.String(length=50), nullable=True),
    sa.Column('posRank', sa.Integer(), nullable=True),
    sa.Column('acquisitionType', sa.String(length=50), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('projected_points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['leagueId'], ['leagues.leagueId'], ),
    sa.ForeignKeyConstraint(['year'], ['leagues.year'], ),
    sa.PrimaryKeyConstraint('playerId')
    )
    op.create_index('idx_player_league_year', 'players', ['leagueId', 'year'], unique=False)
    op.create_index('idx_player_name', 'players', ['name'], unique=False)
    op.create_index('idx_player_position', 'players', ['position'], unique=False)
    op.create_table('settings',
    sa.Column('settingsId', sa.Integer(), nullable=False),
    sa.Column('leagueId', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('regularSeasonCount', sa.Integer(), nullable=True),
    sa.Column('vetoVotesRequired', sa.Integer(), nullable=True),
    sa.Column('teamCount', sa.Integer(), nullable=True),
    sa.Column('playoffTeamCount', sa.Integer(), nullable=True),
    sa.Column('keeperCount', sa.Integer(), nullable=True),
    sa.Column('tradeDeadline', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tieRule', sa.Integer(), nullable=True),
    sa.Column('playoffTieRule', sa.Integer(), nullable=True),
    sa.Column('playoffSeedTieRule', sa.Integer(), nullable=True),
    sa.Column('playoffMatchupPeriodLength', sa.Integer(), nullable=True),
    sa.Column('faab', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['leagueId'], ['leagues.leagueId'], ),
    sa.ForeignKeyConstraint(['year'], ['leagues.year'], ),
    sa.PrimaryKeyConstraint('settingsId'),
    sa.UniqueConstraint('leagueId', 'year', name='uix_settings_league_year')
    )
    op.create_index('idx_settings_league_year', 'settings', ['leagueId', 'year'], unique=False)
    op.create_table('teams',
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('leagueId', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('teamAbbrv', sa.String(length=10), nullable=False),
    sa.Column('teamName', sa.String(length=255), nullable=False),
    sa.Column('divisionId', sa.String(length=255), nullable=True),
    sa.Column('divisionName', sa.String(length=255), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('pointsFor', sa.Integer(), nullable=True),
    sa.Column('pointsAgainst', sa.Integer(), nullable=True),
    sa.Column('waiverRank', sa.Integer(), nullable=True),
    sa.Column('acquisitions', sa.Integer(), nullable=True),
    sa.Column('acquisitionBudgetSpent', sa.Integer(), nullable=True),
    sa.Column('drops', sa.Integer(), nullable=True),
    sa.Column('trades', sa.Integer(), nullable=True),
    sa.Column('streakType', sa.String(length=50), nullable=True),
    sa.Column('streakLength', sa.Integer(), nullable=True),
    sa.Column('standing', sa.Integer(), nullable=True),
    sa.Column('finalStanding', sa.Integer(), nullable=True),
    sa.Column('draftProjRank', sa.Integer(), nullable=True),
    sa.Column('playoffPct', sa.Integer(), nullable=True),
    sa.Column('logoUrl', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['leagueId'], ['leagues.leagueId'], ),
    sa.ForeignKeyConstraint(['year'], ['leagues.year'], ),
    sa.PrimaryKeyConstraint('teamId'),
    sa.UniqueConstraint('teamId', 'year', name='uix_team_year')
    )
    op.create_index('idx_team_league_year', 'teams', ['leagueId', 'year'], unique=False)
    op.create_table('activities',
    sa.Column('activityId', sa.Integer(), nullable=False),
    sa.Column('leagueId', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('playerId', sa.Integer(), nullable=False),
    sa.Column('bidAmount', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['leagueId'], ['leagues.leagueId'], ),
    sa.ForeignKeyConstraint(['playerId'], ['players.playerId'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.teamId'], ),
    sa.ForeignKeyConstraint(['year'], ['leagues.year'], ),
    sa.PrimaryKeyConstraint('activityId')
    )
    op.create_index('idx_activity_league_year', 'activities', ['leagueId', 'year'], unique=False)
    op.create_index('idx_activity_team', 'activities', ['teamId'], unique=False)
    op.create_table('drafts',
    sa.Column('draftId', sa.Integer(), nullable=False),
    sa.Column('leagueId', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('playerId', sa.Integer(), nullable=False),
    sa.Column('roundNum', sa.Integer(), nullable=False),
    sa.Column('roundPick', sa.Integer(), nullable=False),
    sa.Column('keeperStatus', sa.Boolean(), nullable=True),
    sa.Column('bidAmount', sa.Integer(), nullable=True),
    sa.Column('nominatingTeamId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leagueId'], ['leagues.leagueId'], ),
    sa.ForeignKeyConstraint(['nominatingTeamId'], ['teams.teamId'], ),
    sa.ForeignKeyConstraint(['playerId'], ['players.playerId'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.teamId'], ),
    sa.ForeignKeyConstraint(['year'], ['leagues.year'], ),
    sa.PrimaryKeyConstraint('draftId'),
    sa.UniqueConstraint('teamId', 'playerId', 'year', name='uix_draft_pick')
    )
    op.create_index('idx_draft_league_year', 'drafts', ['leagueId', 'year'], unique=False)
    op.create_index('idx_draft_team', 'drafts', ['teamId'], unique=False)
    op.create_table('matchups',
    sa.Column('matchupId', sa.Integer(), nullable=False),
    sa.Column('leagueId', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('homeTeamId', sa.Integer(), nullable=False),
    sa.Column('awayTeamId', sa.Integer(), nullable=False),
    sa.Column('homeScore', sa.Float(), nullable=True),
    sa.Column('awayScore', sa.Float(), nullable=True),
    sa.Column('isPlayoff', sa.Boolean(), nullable=True),
    sa.Column('matchupType', sa.String(length=50), nullable=True),
    sa.Column('winnerTeamId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['awayTeamId'], ['teams.teamId'], ),
    sa.ForeignKeyConstraint(['homeTeamId'], ['teams.teamId'], ),
    sa.ForeignKeyConstraint(['leagueId'], ['leagues.leagueId'], ),
    sa.ForeignKeyConstraint(['winnerTeamId'], ['teams.teamId'], ),
    sa.ForeignKeyConstraint(['year'], ['leagues.year'], ),
    sa.PrimaryKeyConstraint('matchupId')
    )
    op.create_index('idx_matchup_league_year', 'matchups', ['leagueId', 'year'], unique=False)
    op.create_index('idx_matchup_week', 'matchups', ['week'], unique=False)
    op.create_table('rosters',
    sa.Column('rosterId', sa.Integer(), nullable=False),
    sa.Column('leagueId', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('playerId', sa.Integer(), nullable=False),
    sa.Column('rosterSlot', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['leagueId'], ['leagues.leagueId'], ),
    sa.ForeignKeyConstraint(['playerId'], ['players.playerId'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.teamId'], ),
    sa.ForeignKeyConstraint(['year'], ['leagues.year'], ),
    sa.PrimaryKeyConstraint('rosterId'),
    sa.UniqueConstraint('teamId', 'playerId', 'year', name='uix_roster_team_player_year')
    )
    op.create_index('idx_roster_league_year', 'rosters', ['leagueId', 'year'], unique=False)
    op.create_index('idx_roster_team', 'rosters', ['teamId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_roster_team', table_name='rosters')
    op.drop_index('idx_roster_league_year', table_name='rosters')
    op.drop_table('rosters')
    op.drop_index('idx_matchup_week', table_name='matchups')
    op.drop_index('idx_matchup_league_year', table_name='matchups')
    op.drop_table('matchups')
    op.drop_index('idx_draft_team', table_name='drafts')
    op.drop_index('idx_draft_league_year', table_name='drafts')
    op.drop_table('drafts')
    op.drop_index('idx_activity_team', table_name='activities')
    op.drop_index('idx_activity_league_year', table_name='activities')
    op.drop_table('activities')
    op.drop_index('idx_team_league_year', table_name='teams')
    op.drop_table('teams')
    op.drop_index('idx_settings_league_year', table_name='settings')
    op.drop_table('settings')
    op.drop_index('idx_player_position', table_name='players')
    op.drop_index('idx_player_name', table_name='players')
    op.drop_index('idx_player_league_year', table_name='players')
    op.drop_table('players')
    op.drop_index('idx_league_year', table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
