"""Add year to draft table again

Revision ID: 77704d8a20ba
Revises: df3f884e3126
Create Date: 2024-12-30 14:42:58.427170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77704d8a20ba'
down_revision: Union[str, None] = 'df3f884e3126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'year')
    # ### end Alembic commands ###
