"""added espnId to players

Revision ID: 8e30060d7332
Revises: dc669a509dbf
Create Date: 2025-01-04 15:05:55.277846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e30060d7332'
down_revision: Union[str, None] = 'dc669a509dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('espnId', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'players', ['espnId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'espnId')
    # ### end Alembic commands ###
