"""Draft table updated

Revision ID: b47e6ffd5115
Revises: af3bcd3ee33f
Create Date: 2025-01-04 22:17:09.303629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b47e6ffd5115'
down_revision: Union[str, None] = 'af3bcd3ee33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('overallPick', sa.Integer(), nullable=False))
    op.drop_index('idx_draft_league_year', table_name='drafts')
    op.drop_constraint('uix_draft_pick', 'drafts', type_='unique')
    op.create_unique_constraint('uix_draft_pick', 'drafts', ['team_id', 'player_id'])
    op.create_index('idx_draft_team_player_year', 'drafts', ['team_id', 'player_id'], unique=False)
    op.drop_constraint('drafts_league_id_fkey', 'drafts', type_='foreignkey')
    op.drop_column('drafts', 'league_id')
    op.drop_column('drafts', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('drafts', sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('drafts_league_id_fkey', 'drafts', 'leagues', ['league_id'], ['id'])
    op.drop_index('idx_draft_team_player_year', table_name='drafts')
    op.drop_constraint('uix_draft_pick', 'drafts', type_='unique')
    op.create_unique_constraint('uix_draft_pick', 'drafts', ['team_id', 'player_id', 'year'])
    op.create_index('idx_draft_league_year', 'drafts', ['league_id', 'year'], unique=False)
    op.drop_column('drafts', 'overallPick')
    # ### end Alembic commands ###
