"""removed unique espnid/name constraint on Player

Revision ID: cce8140be58b
Revises: 2ee3a7c5c63b
Create Date: 2025-01-04 15:51:16.282556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce8140be58b'
down_revision: Union[str, None] = '2ee3a7c5c63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_player_espnId_name', 'players', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_player_espnId_name', 'players', ['espnId', 'name'])
    # ### end Alembic commands ###
