"""modified settings table, value types were incorrect

Revision ID: d8bf205cbf7b
Revises: 42497e04be8f
Create Date: 2025-01-04 21:58:21.383547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8bf205cbf7b'
down_revision: Union[str, None] = '42497e04be8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
