"""minimized player table to name/id/pos

Revision ID: dc669a509dbf
Revises: 71bd00842110
Create Date: 2025-01-04 14:50:19.113650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc669a509dbf'
down_revision: Union[str, None] = '71bd00842110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_player_league_year', table_name='players')
    op.drop_constraint('uix_player_league_year', 'players', type_='unique')
    op.drop_constraint('players_league_id_fkey', 'players', type_='foreignkey')
    op.drop_column('players', 'points')
    op.drop_column('players', 'proTeam')
    op.drop_column('players', 'projected_points')
    op.drop_column('players', 'posRank')
    op.drop_column('players', 'acquisitionType')
    op.drop_column('players', 'playerId')
    op.drop_column('players', 'league_id')
    op.drop_column('players', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('playerId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('acquisitionType', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('posRank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('projected_points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('proTeam', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('players_league_id_fkey', 'players', 'leagues', ['league_id'], ['id'])
    op.create_unique_constraint('uix_player_league_year', 'players', ['playerId', 'league_id', 'year'])
    op.create_index('idx_player_league_year', 'players', ['league_id', 'year'], unique=False)
    # ### end Alembic commands ###
