"""updated drafts table

Revision ID: 00f5ea68fa5d
Revises: 
Create Date: 2025-02-03 10:24:51.701137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00f5ea68fa5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leagueId', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('teamCount', sa.Integer(), nullable=False),
    sa.Column('currentWeek', sa.Integer(), nullable=False),
    sa.Column('nflWeek', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leagueId', 'year', name='uix_league_year')
    )
    op.create_index('idx_league_composite', 'leagues', ['leagueId', 'year'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espnId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espnId')
    )
    op.create_index('idx_player_name', 'players', ['name'], unique=False)
    op.create_index('idx_player_position', 'players', ['position'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('regularSeasonCount', sa.Integer(), nullable=True),
    sa.Column('vetoVotesRequired', sa.Integer(), nullable=True),
    sa.Column('teamCount', sa.Integer(), nullable=True),
    sa.Column('playoffTeamCount', sa.Integer(), nullable=True),
    sa.Column('keeperCount', sa.Integer(), nullable=True),
    sa.Column('tradeDeadline', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tieRule', sa.String(length=50), nullable=True),
    sa.Column('playoffTieRule', sa.String(length=50), nullable=True),
    sa.Column('playoffSeedTieRule', sa.String(length=50), nullable=True),
    sa.Column('playoffMatchupPeriodLength', sa.Integer(), nullable=True),
    sa.Column('faab', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id')
    )
    op.create_index('idx_settings_league', 'settings', ['league_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('teamAbbrv', sa.String(length=10), nullable=False),
    sa.Column('teamName', sa.String(length=255), nullable=False),
    sa.Column('owners', sa.String(length=50), nullable=True),
    sa.Column('divisionId', sa.String(length=255), nullable=True),
    sa.Column('divisionName', sa.String(length=255), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('pointsFor', sa.Integer(), nullable=True),
    sa.Column('pointsAgainst', sa.Integer(), nullable=True),
    sa.Column('waiverRank', sa.Integer(), nullable=True),
    sa.Column('acquisitions', sa.Integer(), nullable=True),
    sa.Column('acquisitionBudgetSpent', sa.Integer(), nullable=True),
    sa.Column('drops', sa.Integer(), nullable=True),
    sa.Column('trades', sa.Integer(), nullable=True),
    sa.Column('streakType', sa.String(length=50), nullable=True),
    sa.Column('streakLength', sa.Integer(), nullable=True),
    sa.Column('standing', sa.Integer(), nullable=True),
    sa.Column('finalStanding', sa.Integer(), nullable=True),
    sa.Column('draftProjRank', sa.Integer(), nullable=True),
    sa.Column('playoffPct', sa.Integer(), nullable=True),
    sa.Column('logoUrl', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teamId', 'year', name='uix_team_year')
    )
    op.create_index('idx_team_league_year', 'teams', ['league_id', 'year'], unique=False)
    op.create_index('idx_team_year', 'teams', ['teamId', 'year'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('bidAmount', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_team', 'activities', ['team_id'], unique=False)
    op.create_index('idx_activity_team_player', 'activities', ['team_id', 'player_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('overallPick', sa.Integer(), nullable=False),
    sa.Column('roundNum', sa.Integer(), nullable=False),
    sa.Column('roundPick', sa.Integer(), nullable=False),
    sa.Column('keeperStatus', sa.Boolean(), nullable=True),
    sa.Column('bidAmount', sa.Integer(), nullable=False),
    sa.Column('nominating_team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nominating_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'player_id', name='uix_draft_pick')
    )
    op.create_index('idx_draft_team_player_year', 'drafts', ['team_id', 'player_id'], unique=False)
    op.create_table('matchups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('homeScore', sa.Float(), nullable=True),
    sa.Column('awayScore', sa.Float(), nullable=True),
    sa.Column('isPlayoff', sa.Boolean(), nullable=True),
    sa.Column('matchupType', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week', 'home_team_id', 'away_team_id', name='uix_matchup')
    )
    op.create_index('idx_matchup_team_week', 'matchups', ['home_team_id', 'away_team_id', 'week'], unique=False)
    op.create_index('idx_matchup_week', 'matchups', ['week'], unique=False)
    op.create_table('rosters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('rosterSlot', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'player_id', name='uix_roster_team_player')
    )
    op.create_index('idx_roster_team', 'rosters', ['team_id'], unique=False)
    op.create_index('idx_roster_team_player', 'rosters', ['team_id', 'player_id'], unique=False)
    #op.drop_table('goose_db_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('goose_db_version',
    #sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('version_id', sa.BIGINT(), autoincrement=False, nullable=False),
    #sa.Column('is_applied', sa.BOOLEAN(), autoincrement=False, nullable=False),
    #sa.Column('tstamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    #sa.PrimaryKeyConstraint('id', name='goose_db_version_pkey')
    #)
    op.drop_index('idx_roster_team_player', table_name='rosters')
    op.drop_index('idx_roster_team', table_name='rosters')
    op.drop_table('rosters')
    op.drop_index('idx_matchup_week', table_name='matchups')
    op.drop_index('idx_matchup_team_week', table_name='matchups')
    op.drop_table('matchups')
    op.drop_index('idx_draft_team_player_year', table_name='drafts')
    op.drop_table('drafts')
    op.drop_index('idx_activity_team_player', table_name='activities')
    op.drop_index('idx_activity_team', table_name='activities')
    op.drop_table('activities')
    op.drop_index('idx_team_year', table_name='teams')
    op.drop_index('idx_team_league_year', table_name='teams')
    op.drop_table('teams')
    op.drop_index('idx_settings_league', table_name='settings')
    op.drop_table('settings')
    op.drop_index('idx_player_position', table_name='players')
    op.drop_index('idx_player_name', table_name='players')
    op.drop_table('players')
    op.drop_index('idx_league_composite', table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
