"""updated drafts table, nom team id, null

Revision ID: 1b8f3a3e200f
Revises: 7e3e2a80de5f
Create Date: 2025-02-03 10:40:01.621276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8f3a3e200f'
down_revision: Union[str, None] = '7e3e2a80de5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drafts', 'nominating_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drafts', 'nominating_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
