"""updated drafts table, no nulls

Revision ID: 7e3e2a80de5f
Revises: 00f5ea68fa5d
Create Date: 2025-02-03 10:25:49.958063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3e2a80de5f'
down_revision: Union[str, None] = '00f5ea68fa5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drafts', 'keeperStatus',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drafts', 'keeperStatus',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
